name: openai-testing-agent-demo

services:
  apps:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - ${FRONTEND_HOST:-127.0.0.1:3000}:3000
      - ${SAMPLE_APP_HOST:-127.0.0.1:3005}:3005
      - ${CUA_SERVER_HOST:-127.0.0.1:8080}:8080